### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/pms#175]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_asset_pms
- [ ] mis_builder_pms
- [ ] multi_pms_properties - #270
- [ ] pms - #270
- [ ] pms_account_move_budget
- [ ] pms_housekeeping
- [ ] pms_hr_property
- [ ] pms_l10n_es
- [ ] pms_l10n_es_sii
- [ ] pms_rooming_xls
- [ ] pos_pms_link

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by BitStab** [comment]
I'd work on it, but i'd like to change some principals:

Create a sales order instead of directly creating account moves from folio (f.e. one order per housing unit) this would make it easier to split up, if customers pay per room, not per reservation. Also it needs to be adapted to the Analytics replicated by OCA, as 16.0 doesn't contain analytic tags anymore.

What do you think about using sales order, instead of directly creating the account move on invoicing? I mean by approaching the normal sales flow we could assure to keep the standard invoicing methods applied including all steps, any localization is applying to it. Actually this is not the case in 14.0

Cheers

**Comment by BurningNacho** [comment]
I want to use this module in a v16 community, I'll try to do my best to implement a version for the branch 16.0 and hopefully add a PR. I don't have much experience with this git workflow but I'll do my best checking all the documentation and requirements for OCA!
Any help is kindly appreciated!
